version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      # Install Dependencies
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      # Test (if any)
      # Build
      - echo Creating build file...
      - yarn run build
  post_build:
    commands:
      # Sync with S3
      - echo Syncing with S3...
      - aws s3 sync ./build s3://www.wontonwarrior.com.au/ --delete
      # Clear Cloudfront cache
      - echo Creating cloudfront invalidation...
      - aws cloudfront create-invalidation --distribution-id E2UNQU2LHY3W1Z --paths '/*'
