version: '3.7'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm start
    stdin_open: true # Address this issue https://github.com/facebook/create-react-app/issues/8688
